# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Spelling
version:      0.10
version_from: lib/Test/Spelling.pm
installdirs:  site
requires:
    File::Spec:                    0
    Pod::Spell:                    1.01
    Test::Builder::Tester:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
